[functions.latido_push_notification]
verify_jwt = false

[functions.latido_message_email]
verify_jwt = false

[functions.create_business_lead_alert_stripe_webhook]
verify_jwt = false

[functions.latido_business_lead_alert_email]
verify_jwt = false
