const PRINT_BASE_URL = 'https://www.latido.ch/club/prints'

function cafeMockups({ colorLabel, garment, ink, selection, exactFront }) {
  const selections = selection ? { Color: selection } : undefined
  const base = `/club/products/camiseta-base-${garment}.webp`
  return [
    exactFront
      ? { url: exactFront, label: `Frontal · ${colorLabel}`, ...(selections ? { selections } : {}) }
      : {
          url: base,
          base,
          overlay: `/club/designs/cafe-frontal-${ink}.webp`,
          placement: 'front',
          label: `Frontal · ${colorLabel}`,
          ...(selections ? { selections } : {}),
        },
    {
      url: base,
      base,
      overlay: `/club/designs/cafe-trasera-${ink}-v2.png`,
      placement: 'cafe-back-v2',
      label: `Trasera · ${colorLabel}`,
      ...(selections ? { selections } : {}),
    },
  ]
}

function hablasMockups({ colorLabel, garment, selection, exactFront, exactBack }) {
  const selections = { Color: selection }
  const base = `/club/products/camiseta-base-${garment}.webp`
  return [
    exactFront
      ? { url: exactFront, label: `Frontal · ${colorLabel}`, selections }
      : {
          url: base,
          base,
          overlay: '/club/products/hablas-espanol-granate-frontal.webp',
          placement: 'hablas-front',
          label: `Frontal · ${colorLabel}`,
          selections,
        },
    exactBack
      ? { url: exactBack, label: `Trasera · ${colorLabel}`, selections }
      : {
          url: base,
          base,
          overlay: '/club/products/hablas-espanol-granate-trasera.webp',
          placement: 'hablas-back',
          label: `Trasera · ${colorLabel}`,
          selections,
        },
  ]
}

export const GELATO_STOREFRONT = {
  storeName: 'Latido Club',
  products: [
    {
      id: '5dd70f64-e112-4cfb-88b1-5cdc18d257c3',
      name: 'Camiseta Café · Texto blanco',
      category: 'camisetas',
      price: 36.9,
      compareAtPrice: 39.9,
      shortName: 'Camiseta Café · Blanco',
      eyebrow: 'Café 6.50 CHF',
      description: 'Camiseta unisex negra de algodón de alto gramaje con el diseño Café en blanco.',
      material: '100% algodón · Alto gramaje',
      accent: '#8FA5FF',
      imageFallback: '/club/products/camiseta-cafe-texto-blanco-negra.webp',
      imageAlt: 'Camiseta negra Café con texto blanco de Latido Club',
      galleryImages: [
        ...cafeMockups({
          colorLabel: 'Negro',
          garment: 'negra',
          ink: 'blanco',
          exactFront: '/club/products/camiseta-cafe-texto-blanco-negra.webp',
        }),
      ],
    },
    {
      id: '588088c0-6780-41c2-a67f-201ecf5f0eb2',
      name: 'Camiseta Café · Texto lavanda',
      category: 'camisetas',
      price: 36.9,
      compareAtPrice: 39.9,
      shortName: 'Camiseta Café · Lavanda',
      eyebrow: 'Café 6.50 CHF',
      description: 'Camiseta unisex de algodón de alto gramaje con el diseño Café en lavanda. Disponible en blanco, natural y negro.',
      material: '100% algodón · Alto gramaje',
      accent: '#8FA5FF',
      imageFallback: '/club/products/camiseta-cafe-texto-lavanda-blanca.webp',
      imageAlt: 'Camiseta Café con texto lavanda de Latido Club',
      galleryImages: [
        ...cafeMockups({ colorLabel: 'Blanco', garment: 'blanca', ink: 'lavanda', selection: 'Blanco', exactFront: '/club/products/camiseta-cafe-texto-lavanda-blanca.webp' }),
        ...cafeMockups({ colorLabel: 'Natural', garment: 'natural', ink: 'lavanda', selection: 'Natural' }),
        ...cafeMockups({ colorLabel: 'Negro', garment: 'negra', ink: 'lavanda', selection: 'Negro' }),
      ],
    },
    {
      id: 'b6b8be91-6cfd-42d2-88f3-bed61406fe2f',
      name: 'Camiseta Café · Texto negro',
      category: 'camisetas',
      price: 36.9,
      compareAtPrice: 39.9,
      shortName: 'Camiseta Café · Negro',
      eyebrow: 'Café 6.50 CHF',
      description: 'Camiseta unisex de algodón de alto gramaje con el diseño Café en negro. Disponible en blanco, natural y gris claro.',
      material: '100% algodón · Alto gramaje',
      accent: '#10204A',
      imageFallback: '/club/products/camiseta-cafe-texto-negro-blanca.webp',
      imageAlt: 'Camiseta Café con texto negro de Latido Club',
      galleryImages: [
        ...cafeMockups({ colorLabel: 'Blanco', garment: 'blanca', ink: 'negro', selection: 'Blanco', exactFront: '/club/products/camiseta-cafe-texto-negro-blanca.webp' }),
        ...cafeMockups({ colorLabel: 'Natural', garment: 'natural', ink: 'negro', selection: 'Natural', exactFront: '/club/products/camiseta-cafe-texto-negro-natural.webp' }),
        ...cafeMockups({ colorLabel: 'Gris claro', garment: 'gris', ink: 'negro', selection: 'Ash', exactFront: '/club/products/camiseta-cafe-texto-negro-gris.webp' }),
      ],
    },
    {
      id: 'c5fe22ad-0172-4582-83ec-b713487b18fb',
      name: 'Camiseta Café · Texto granate',
      category: 'camisetas',
      price: 36.9,
      compareAtPrice: 39.9,
      shortName: 'Camiseta Café · Granate',
      eyebrow: 'Café 6.50 CHF',
      description: 'Camiseta unisex de algodón de alto gramaje con el diseño Café en granate. Disponible en blanco, natural y gris claro.',
      material: '100% algodón · Alto gramaje',
      accent: '#9E1B20',
      imageFallback: '/club/products/camiseta-cafe-texto-granate-blanca.webp',
      imageAlt: 'Camiseta Café con texto granate de Latido Club',
      galleryImages: [
        ...cafeMockups({ colorLabel: 'Blanco', garment: 'blanca', ink: 'granate', selection: 'Blanco', exactFront: '/club/products/camiseta-cafe-texto-granate-blanca.webp' }),
        ...cafeMockups({ colorLabel: 'Natural', garment: 'natural', ink: 'granate', selection: 'Natural' }),
        ...cafeMockups({ colorLabel: 'Gris claro', garment: 'gris', ink: 'granate', selection: 'Ash' }),
      ],
    },
    {
      id: '1759e8a1-03e1-40eb-947b-de41f50490c3',
      name: 'Sudadera Logo Latido Club · Negra',
      category: 'sudaderas',
      price: 46.9,
      compareAtPrice: 49.9,
      shortName: 'Sudadera Logo Latido Club · Negra',
      eyebrow: 'Firma Latido Club',
      description: 'Sudadera unisex negra de tejido polar suave con la firma de Latido Club en blanco.',
      material: '80% algodón · 20% poliéster',
      accent: '#FF4557',
      imageFallback: '/club/products/sudadera-logo-negra-frontal.png',
      imageAlt: 'Sudadera negra con el logo Latido Club en blanco',
      galleryImages: [
        { url: '/club/products/sudadera-logo-negra-frontal.png', label: 'Frontal' },
        { url: '/club/products/sudadera-logo-negra-trasera.webp', label: 'Diseño trasero' },
      ],
      maxImages: 2,
    },
    {
      id: 'e2a521ea-ebab-4709-80c1-12b173b13271',
      name: 'Sudadera Logo Latido Club · Colores claros',
      category: 'sudaderas',
      price: 46.9,
      compareAtPrice: 49.9,
      shortName: 'Sudadera Logo Latido Club · Clara',
      eyebrow: 'Firma Latido Club',
      description: 'Sudadera unisex de tejido polar suave con la firma de Latido Club en negro. Disponible en blanco, arena y gris.',
      material: '80% algodón · 20% poliéster',
      accent: '#1757E8',
      imageFallback: '/club/products/sudadera-logo-blanca-frontal.png',
      imageAlt: 'Sudadera clara con el logo Latido Club en negro',
      galleryImages: [
        { url: '/club/products/sudadera-logo-blanca-frontal.png', label: 'Frontal · Blanco', selections: { Color: 'Blanco' } },
        { url: '/club/products/sudadera-logo-blanca-trasera.webp', label: 'Diseño trasero · Blanco', selections: { Color: 'Blanco' } },
        { url: '/club/products/sudadera-logo-arena-frontal.png', label: 'Frontal · Arena', selections: { Color: 'Arena' } },
        { url: '/club/products/sudadera-logo-arena-trasera.webp', label: 'Diseño trasero · Arena', selections: { Color: 'Arena' } },
        { url: '/club/products/sudadera-logo-gris-frontal.png', label: 'Frontal · Gris', selections: { Color: 'ring spun sports grey' } },
        { url: '/club/products/sudadera-logo-gris-trasera.webp', label: 'Diseño trasero · Gris', selections: { Color: 'ring spun sports grey' } },
      ],
      maxImages: 4,
    },
    {
      id: '9b2e0872-ffc6-4bbe-8615-eec669e36da4',
      name: 'Bolsa Logo Latido Club',
      category: 'bolsas',
      price: 24.9,
      purchaseType: 'addon',
      shortName: 'Bolsa Logo Latido Club',
      eyebrow: 'Firma Latido Club',
      description: 'Bolsa de algodón natural con la firma de Latido Club, asas largas y espacio para el día a día.',
      material: '100% algodón · 10 litros',
      accent: '#00B3A4',
      imageFallback: '/brand/latido-horizontal-black.webp',
      imageAlt: 'Bolsa de tela natural con el logo Latido Club',
      maxImages: 2,
    },
    {
      id: 'e23cd355-eb48-4844-862a-98592e7757f7',
      name: 'Camiseta Logo Latido Club · Negra',
      category: 'camisetas',
      price: 36.9,
      compareAtPrice: 39.9,
      shortName: 'Camiseta Logo Latido Club · Negra',
      eyebrow: 'Símbolo Latido',
      description: 'Camiseta unisex negra de algodón de alto gramaje con el símbolo multicolor y el nombre de Latido Club en blanco.',
      material: 'Algodón de alto gramaje',
      accent: '#FF4557',
      imageFallback: '/club/products/camiseta-logo-negra-frontal.png',
      imageAlt: 'Camiseta negra con el logo Latido Club en blanco',
      galleryImages: [
        { url: '/club/products/camiseta-logo-negra-frontal.png', label: 'Frontal' },
        { url: '/club/products/camiseta-logo-negra-trasera.webp', label: 'Diseño trasero' },
      ],
      maxImages: 2,
    },
    {
      id: '0541177c-34b6-4fb4-bd91-64bd5a087c08',
      name: 'Camiseta Logo Latido Club · Colores claros',
      category: 'camisetas',
      price: 36.9,
      compareAtPrice: 39.9,
      shortName: 'Camiseta Logo Latido Club · Clara',
      eyebrow: 'Símbolo Latido',
      description: 'Camiseta unisex de algodón de alto gramaje con el símbolo multicolor. Disponible en blanco, natural y gris.',
      material: 'Algodón de alto gramaje',
      accent: '#1757E8',
      imageFallback: '/club/products/camiseta-logo-blanca-frontal.png',
      imageAlt: 'Camiseta clara con el logo Latido Club en negro',
      galleryImages: [
        { url: '/club/products/camiseta-logo-blanca-frontal.png', label: 'Frontal · Blanco', selections: { Color: 'Blanco' } },
        { url: '/club/products/camiseta-logo-blanca-trasera.webp', label: 'Diseño trasero · Blanco', selections: { Color: 'Blanco' } },
        { url: '/club/products/camiseta-logo-natural-frontal.png', label: 'Frontal · Natural', selections: { Color: 'Natural' } },
        { url: '/club/products/camiseta-logo-natural-trasera.webp', label: 'Diseño trasero · Natural', selections: { Color: 'Natural' } },
        { url: '/club/products/camiseta-logo-gris-frontal.png', label: 'Frontal · Gris', selections: { Color: 'Ash' } },
        { url: '/club/products/camiseta-logo-gris-trasera.webp', label: 'Diseño trasero · Gris', selections: { Color: 'Ash' } },
      ],
      maxImages: 4,
    },
    {
      id: 'c1b3d3ef-dd71-4d78-8712-4d7fea26880b',
      titleIncludes: 'Hablas Español',
      category: 'camisetas',
      price: 36.9,
      compareAtPrice: 39.9,
      name: 'Camiseta ¿Tú también hablas español?',
      shortName: 'Camiseta Hablas Español',
      eyebrow: 'Diseño tipográfico',
      description: 'Camiseta unisex de algodón de alto gramaje: mensaje minimalista delante y diseño granate grande en la espalda.',
      material: 'Algodón de alto gramaje',
      accent: '#2161E8',
      imageFallback: '/club/products/camiseta-hablas-blanca-frontal.webp',
      imageAlt: 'Camiseta con diseño granate de Latido Club',
      galleryImages: [
        ...hablasMockups({
          colorLabel: 'Blanco',
          garment: 'blanca',
          selection: 'Blanco',
          exactFront: '/club/products/camiseta-hablas-blanca-frontal.webp',
          exactBack: '/club/camiseta-hablas-espanol-espalda.png?v=2',
        }),
        ...hablasMockups({ colorLabel: 'Natural', garment: 'natural', selection: 'Natural' }),
        ...hablasMockups({ colorLabel: 'Gris claro', garment: 'gris', selection: 'Ash' }),
        ...hablasMockups({ colorLabel: 'Negro', garment: 'negra', selection: 'Negro' }),
      ],
      fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
      fileType: 'default',
    },
    {
      id: 'bd807369-b74d-483d-9065-fb994ca7bb38',
      titleIncludes: 'Hablas Español / Granate',
      category: 'bolsas',
      price: 24.9,
      purchaseType: 'addon',
      name: 'Bolsa ¿Tú también hablas español?',
      shortName: 'Bolsa Hablas Español',
      eyebrow: 'Diseño tipográfico',
      description: 'Bolsa de algodón natural con el diseño granate, asas largas, costuras reforzadas y 10 litros de capacidad.',
      material: '100% algodón · 10 litros',
      accent: '#9E1B20',
      imageFallback: '/club/totebag-hablas-espanol-granate.jpg',
      imageAlt: 'Bolsa de tela natural Hablas Español de Latido Club',
      optionLabel: 'Color',
    },
    {
      id: 'f3ff3398-9981-496f-b9d3-4602be85b15b',
      titleIncludes: 'Sudadera Unisex / Hablas Español',
      name: 'Sudadera ¿Tú también hablas español?',
      category: 'sudaderas',
      price: 46.9,
      compareAtPrice: 49.9,
      shortName: 'Sudadera Hablas Español',
      eyebrow: 'Diseño tipográfico',
      description: 'Sudadera unisex de tejido polar suave con el diseño granate ¿Tú también hablas español? Disponible en cuatro colores.',
      material: '80% algodón · 20% poliéster',
      accent: '#9E1B20',
      imageFallback: '/club/sudadera-hablas-espanol-frontal.jpg',
      imageAlt: 'Sudadera ¿Tú también hablas español? de Latido Club',
      galleryImages: [
        { url: '/club/sudadera-hablas-espanol-frontal.jpg', label: 'Frontal · Blanco', selections: { Color: 'Blanco' } },
        { url: '/club/sudadera-hablas-espanol-espalda.png', label: 'Diseño trasero · Blanco', selections: { Color: 'Blanco' } },
        { url: '/club/products/sudadera-hablas-arena-frontal.webp', label: 'Frontal · Arena', selections: { Color: 'Arena' } },
        { url: '/club/products/sudadera-hablas-arena-trasera.webp', label: 'Diseño trasero · Arena', selections: { Color: 'Arena' } },
        { url: '/club/products/sudadera-hablas-gris-frontal.webp', label: 'Frontal · Gris', selections: { Color: 'ring spun sports grey' } },
        { url: '/club/products/sudadera-hablas-gris-trasera.webp', label: 'Diseño trasero · Gris', selections: { Color: 'ring spun sports grey' } },
        { url: '/club/products/sudadera-hablas-negra-frontal.webp', label: 'Frontal · Negro', selections: { Color: 'Negro' } },
        { url: '/club/products/sudadera-hablas-negra-trasera.webp', label: 'Diseño trasero · Negro', selections: { Color: 'Negro' } },
      ],
    },
    {
      id: '7e2bab53-6962-4fc7-ab8c-f8009c6f5754',
      titleIncludes: 'Carcasa resistente / Hablas Español',
      category: 'carcasas',
      price: 21.9,
      purchaseType: 'addon',
      name: 'Carcasa ¿Tú también hablas español?',
      shortName: 'Carcasa Hablas Español',
      eyebrow: 'Diseño tipográfico',
      description: 'Carcasa resistente de doble capa con el diseño granate y acabado brillante para proteger el móvil.',
      material: 'Doble capa · Acabado brillante',
      accent: '#9E1B20',
      imageFallback: '/club/carcasa-hablas-espanol.jpg',
      imageAlt: 'Carcasa resistente Hablas Español de Latido Club',
      maxImages: 1,
    },
    {
      id: 'c578978a-3f07-41e9-b715-e71af2e84070',
      category: 'carcasas',
      price: 21.9,
      purchaseType: 'addon',
      name: 'Carcasa resistente Latido Club',
      shortName: 'Carcasa Latido Club',
      eyebrow: 'Símbolo Latido',
      description: 'Carcasa resistente de doble capa con el símbolo de Latido Club y acabado brillante para proteger el móvil.',
      material: 'Doble capa · Acabado brillante',
      accent: '#1757E8',
      imageFallback: '/brand/latido-horizontal-black.webp',
      imageAlt: 'Carcasa resistente con el símbolo de Latido Club',
      maxImages: 1,
    },
    {
      id: '2f6d7770-e062-471d-8966-a0877be0b212',
      category: 'carcasas',
      price: 21.9,
      purchaseType: 'addon',
      name: 'Carcasa resistente Samsung · Latido Club',
      shortName: 'Carcasa Samsung Latido Club',
      eyebrow: 'Símbolo Latido',
      description: 'Carcasa resistente para Samsung con el símbolo de Latido Club, doble capa y acabado brillante.',
      material: 'Doble capa · Acabado brillante',
      accent: '#1757E8',
      imageFallback: '/brand/latido-horizontal-black.webp',
      imageAlt: 'Carcasa resistente Samsung con el símbolo de Latido Club',
      maxImages: 1,
    },
    {
      id: '150f2628-a409-4b1b-ae40-810a53225d9f',
      category: 'carcasas',
      price: 21.9,
      purchaseType: 'addon',
      name: 'Carcasa resistente Samsung · ¿Tú también hablas español?',
      shortName: 'Carcasa Samsung Hablas Español',
      eyebrow: 'Diseño tipográfico',
      description: 'Carcasa resistente para Samsung con el diseño ¿Tú también hablas español?, doble capa y acabado brillante.',
      material: 'Doble capa · Acabado brillante',
      accent: '#9E1B20',
      imageFallback: '/club/products/hablas-espanol-granate-trasera.webp',
      imageAlt: 'Carcasa resistente Samsung con el diseño Hablas Español de Latido Club',
      maxImages: 1,
    },
  ],
}

export const GELATO_CATALOG = {
  'gelato:c1b3d3ef-dd71-4d78-8712-4d7fea26880b:11ef009f-2859-4c9b-99ac-2819cc3cdfbc': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_heavy-weight_gsi_s_gco_white_gpr_4-4_inlbl_gildan_5000',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'gelato:c1b3d3ef-dd71-4d78-8712-4d7fea26880b:08b7a5de-37f5-471b-9f98-eab0ad3693fe': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_heavy-weight_gsi_m_gco_white_gpr_4-4_inlbl_gildan_5000',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'gelato:c1b3d3ef-dd71-4d78-8712-4d7fea26880b:2b498b98-1c0d-4af7-b90b-5a507ed3e18b': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_heavy-weight_gsi_l_gco_white_gpr_4-4_inlbl_gildan_5000',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'gelato:c1b3d3ef-dd71-4d78-8712-4d7fea26880b:c30ed3fb-af5d-4bca-86fd-b0eb7aef7924': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_heavy-weight_gsi_xl_gco_white_gpr_4-4_inlbl_gildan_5000',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'gelato:c1b3d3ef-dd71-4d78-8712-4d7fea26880b:07b3a9ea-1594-4264-81b9-20e6bb1672bc': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_heavy-weight_gsi_2xl_gco_white_gpr_4-4_inlbl_gildan_5000',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'shirt-s': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_classic_gsi_s_gco_white_gpr_4-0',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'shirt-m': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_classic_gsi_m_gco_white_gpr_4-0',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'shirt-l': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_classic_gsi_l_gco_white_gpr_4-0',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'shirt-xl': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_classic_gsi_xl_gco_white_gpr_4-0',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'shirt-xxl': {
    productUid: 'apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_classic_gsi_2xl_gco_white_gpr_4-0',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chica.png`,
  },
  'tote-natural': {
    productUid: 'bag_product_bsc_tote-bag_bqa_clc_bsi_std-t_bco_natural_bpr_4-0',
    fileUrl: `${PRINT_BASE_URL}/hablas-espanol-chico.png`,
  },
  'case-iphone-15': {
    productUid: 'phonecase_apple_iphone-15_tough_white_glossy',
    fileUrl: `${PRINT_BASE_URL}/logo-latido-club.png`,
  },
  'case-iphone-15-pro': {
    productUid: 'phonecase_apple_iphone-15pro_tough_white_glossy',
    fileUrl: `${PRINT_BASE_URL}/logo-latido-club.png`,
  },
  'case-iphone-16': {
    productUid: 'phonecase_apple_iphone-16_tough_white_glossy',
    fileUrl: `${PRINT_BASE_URL}/logo-latido-club.png`,
  },
  'case-iphone-16-pro': {
    productUid: 'phonecase_apple_iphone-16pro_tough_white_glossy',
    fileUrl: `${PRINT_BASE_URL}/logo-latido-club.png`,
  },
}
